/** @type {import('tailwindcss').Config} */
const withAlpha = (name) => `rgb(var(${name}) / <alpha-value>)`;

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-error": withAlpha("--c-on-error"),
        "outline-variant": withAlpha("--c-outline-variant"),
        "surface-dim": withAlpha("--c-surface-dim"),
        "secondary-fixed": withAlpha("--c-secondary-fixed"),
        tertiary: withAlpha("--c-tertiary"),
        "primary-fixed-dim": withAlpha("--c-primary-fixed-dim"),
        "surface-container-low": withAlpha("--c-surface-container-low"),
        "on-secondary-fixed-variant": withAlpha("--c-on-secondary-fixed-variant"),
        "on-surface-variant": withAlpha("--c-on-surface-variant"),
        "surface-tint": withAlpha("--c-surface-tint"),
        "on-primary": withAlpha("--c-on-primary"),
        "on-background": withAlpha("--c-on-background"),
        surface: withAlpha("--c-surface"),
        "surface-container-highest": withAlpha("--c-surface-container-highest"),
        "on-secondary-fixed": withAlpha("--c-on-secondary-fixed"),
        "on-secondary": withAlpha("--c-on-secondary"),
        "primary-fixed": withAlpha("--c-primary-fixed"),
        "secondary-container": withAlpha("--c-secondary-container"),
        "inverse-surface": withAlpha("--c-inverse-surface"),
        "surface-bright": withAlpha("--c-surface-bright"),
        "on-tertiary-fixed": withAlpha("--c-on-tertiary-fixed"),
        "on-surface": withAlpha("--c-on-surface"),
        "tertiary-fixed": withAlpha("--c-tertiary-fixed"),
        "inverse-primary": withAlpha("--c-inverse-primary"),
        error: withAlpha("--c-error"),
        "on-primary-container": withAlpha("--c-on-primary-container"),
        "on-tertiary": withAlpha("--c-on-tertiary"),
        "surface-container-high": withAlpha("--c-surface-container-high"),
        "on-tertiary-container": withAlpha("--c-on-tertiary-container"),
        "surface-variant": withAlpha("--c-surface-variant"),
        "surface-container": withAlpha("--c-surface-container"),
        "tertiary-fixed-dim": withAlpha("--c-tertiary-fixed-dim"),
        secondary: withAlpha("--c-secondary"),
        "on-primary-fixed-variant": withAlpha("--c-on-primary-fixed-variant"),
        "primary-container": withAlpha("--c-primary-container"),
        "error-container": withAlpha("--c-error-container"),
        primary: withAlpha("--c-primary"),
        "secondary-fixed-dim": withAlpha("--c-secondary-fixed-dim"),
        "surface-container-lowest": withAlpha("--c-surface-container-lowest"),
        outline: withAlpha("--c-outline"),
        "inverse-on-surface": withAlpha("--c-inverse-on-surface"),
        "on-tertiary-fixed-variant": withAlpha("--c-on-tertiary-fixed-variant"),
        "on-error-container": withAlpha("--c-on-error-container"),
        "on-secondary-container": withAlpha("--c-on-secondary-container"),
        "tertiary-container": withAlpha("--c-tertiary-container"),
        background: withAlpha("--c-background"),
        "on-primary-fixed": withAlpha("--c-on-primary-fixed"),
      },
      fontFamily: {
        headline: ["Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
